
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PC
 */
public class RecordTable extends javax.swing.JFrame {

    /**
     * Creates new form RecordTable
     */
    public RecordTable() {
        initComponents();
        try {
            show_Voucher();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RecordTable.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
     public ArrayList<Voucher> voucherList() throws ClassNotFoundException, SQLException{
            ArrayList<Voucher> voucherList = new ArrayList<Voucher>();
            
            
            
           
Class.forName("com.mysql.jdbc.Driver");  
    try (java.sql.Connection con = DriverManager.getConnection( "jdbc:mysql://localhost:3306/tvs","root","")) {
        java.sql.Statement stmt=con.createStatement();
        ResultSet rs=stmt.executeQuery("select * from voucher");
        Voucher voucher;
        while(rs.next())
        {
        voucher = new Voucher(rs.getInt("No"),rs.getString("Name"),rs.getString("Date"),rs.getInt("Ammount"),rs.getString("Payment"),rs.getString("Details"));
         voucherList.add(voucher);
       
       
        }
        }
            catch(SQLException e){ System.out.println(e);}
        return voucherList;
     
     }
     
     public void show_Voucher() throws ClassNotFoundException{
        try {
            ArrayList<Voucher> list = voucherList();
            DefaultTableModel Model = (DefaultTableModel)RecordTable.getModel();
            Object[] row = new Object[6];
            for(int i=0; i<list.size(); i++)
            {
            row[0]=list.get(i).getNo(); 
             row[1]=list.get(i).getName();
             row[2]=list.get(i).getDate();
             row[3]=list.get(i).getAmmount(); 
             row[4]=list.get(i).getPayment(); 
             row[5]=list.get(i).getDetails();
             Model.addRow(row);
            
                     }
        } catch (SQLException ex) {
            Logger.getLogger(RecordTable.class.getName()).log(Level.SEVERE, null, ex);
        }
         
     
     
     
     }

            
            
            
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Delete = new javax.swing.JButton();
        Print = new javax.swing.JButton();
        New_V = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        RecordTable = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Delete.setBackground(new java.awt.Color(255, 0, 51));
        Delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Delete.setForeground(new java.awt.Color(0, 0, 204));
        Delete.setText("Delete Record");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Print.setBackground(new java.awt.Color(255, 51, 51));
        Print.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Print.setForeground(new java.awt.Color(0, 0, 153));
        Print.setText("Print Record");
        Print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintActionPerformed(evt);
            }
        });

        New_V.setBackground(new java.awt.Color(255, 51, 51));
        New_V.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        New_V.setForeground(new java.awt.Color(0, 0, 153));
        New_V.setText("New Voucher");
        New_V.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                New_VActionPerformed(evt);
            }
        });

        Back.setBackground(new java.awt.Color(255, 0, 0));
        Back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Back.setForeground(new java.awt.Color(0, 0, 255));
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Delete, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(Print, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(New_V, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(Print, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(New_V, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        RecordTable.setBackground(new java.awt.Color(255, 0, 51));
        RecordTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        RecordTable.setForeground(new java.awt.Color(0, 0, 204));
        RecordTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Voucher NO", "Cous. Name", "Date", "Ammount", "Payment", "Details"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(RecordTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintActionPerformed
      G_Voucher();
    }//GEN-LAST:event_PrintActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
      
Back();        


    }//GEN-LAST:event_BackActionPerformed

    private void New_VActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_New_VActionPerformed


 New_V();
    }//GEN-LAST:event_New_VActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        try {
            delete();        // TODO add your handling code here:
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RecordTable.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(RecordTable.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_DeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecordTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecordTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecordTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecordTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecordTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Delete;
    private javax.swing.JButton New_V;
    private javax.swing.JButton Print;
    private javax.swing.JTable RecordTable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
public void Back(){

    
      java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Detail_Form().setVisible(true);
            }
        });

}


public void New_V(){

 java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new New_Voucher().setVisible(true);
            }
        });



}

public void G_Voucher(){

    
    int row = RecordTable.getSelectedRow();
        if( row<0){
            JOptionPane.showMessageDialog(null,"please, select the record first");
        } else {
            String id = RecordTable.getModel().getValueAt(row, 0).toString();
            
            
            
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    try {
                        new Mainformat(id).setVisible(true);
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(RecordTable.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            });
            
        }}

public void delete() throws ClassNotFoundException, SQLException{
    int row = RecordTable.getSelectedRow();
        if( row<0){
            JOptionPane.showMessageDialog(null,"please, select the record first");
        }
        else{
                String id = RecordTable.getModel().getValueAt(row, 0).toString();
 Class.forName("com.mysql.jdbc.Driver");  
    try (java.sql.Connection con = DriverManager.getConnection( "jdbc:mysql://localhost:3306/tvs","root","")) {
       Statement stmt = con.createStatement(); 
stmt.executeUpdate("DELETE from voucher where No = "+id);

 JOptionPane.showMessageDialog(null,"Record deleted Successfully");
  java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecordTable().setVisible(true);
            }
        });
  

    }
}
}
}
